### ISSUE TITLE
Look for binaries in $PATH instead 

### ISSUE THREAD

**Issue by milgner** [SGDE/sgrandr#3]
On NixOS, the system doesn't follow LSB and so the binaries are not in `/usr/bin` but in a profile folder. See https://nixos.wiki/wiki/Nix_vs._Linux_Standard_Base

So it would be great if `sgrandr` could look for the binaries in `$PATH` instead of hard-coding the path based on LSB.

**Comment by ItsZariep** [comment]
thanks for the info, now the is a <a href="https://github.com/SGDE/SGRandR/blob/4b903f513761c47caff127d9604909029f2ee666/events.h#L143"> function</a> that looks for a file in a path, used to check wlr-randr or xrandr filenames on $PATH, reopen if this workaround is not working correctly
